services:
  user:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    hostname: user
#    ports:
#      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user_postgres/user
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pwd
    depends_on:
      user_postgres:
        condition: service_healthy

  artist:
    build:
      context: ./artist-service
      dockerfile: Dockerfile
    hostname: artist
#    ports:
#      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://artist_mysql/artist
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pwd
    depends_on:
      artist_mysql:
        condition: service_healthy

  podcast:
    build:
      context: ./podcast-service
      dockerfile: Dockerfile
    hostname: podcast
#    ports:
#      - "8083:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - SPRING_DATASOURCE_URL=jdbc:mysql://podcast_mysql/podcast
#      - SPRING_DATASOURCE_USERNAME=user
#      - SPRING_DATASOURCE_PASSWORD=pwd
#    depends_on:
#      podcast_mysql:
#        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      #      - SPRING_DATA_MONGODB_URI=mongodb://user:pwd@mongodb_podcast:27017/podcast?authSource=admin
      #      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      #      - SPRING_DATA_MONGODB_DATABASE=podcast
      #      - SPRING_DATASOURCE_USERNAME=user
      #      - SPRING_DATASOURCE_PASSWORD=pwd
      - SPRING_DATA_MONGODB_HOST=mongodb_podcast
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=user
      - SPRING_DATA_MONGODB_PASSWORD=pwd
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SPRING_DATA_MONGODB_DATABASE=podcast
    depends_on:
        mongodb_podcast:
          condition: service_healthy


  catalog:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    hostname: catalog
#    ports:
#      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://catalog_mysql/catalog
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pwd
    depends_on:
      catalog_mysql:
        condition: service_healthy


  order:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: order
    ports:
      - "8087:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order_postgres/order
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pwd
    depends_on:
      order_postgres:
        condition: service_healthy
  ##############################################
  ################## msql#######################

  user_postgres:
    image: postgres:latest
    container_name: postgres1-user
    hostname: postgres_user
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - PGUSER=user
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=user
    #    volumes:
    #      - ./data/postgres:/var/lib/postgresql/data
    #      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: "pg_isready -h user_postgres"
      interval: 10s
      timeout: 5s
      retries: 5

  order_postgres:
    image: postgres:latest
    container_name: postgres1-order
    hostname: postgres_order
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - PGUSER=user
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=order
    #    volumes:
    #      - ./data/postgres:/var/lib/postgresql/data
    #      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: "pg_isready -h order_postgres"
      interval: 10s
      timeout: 5s
      retries: 5


  #  user_mysql:
#    image: mysql:8
#    ports:
#      - "3307:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=rootpass
#      - MYSQL_DATABASE=user
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=pwd
#    volumes:
#      - ./data/mysql-user:/var/lib/user_mysql
#      - ./data/init.d:/docker-entrypoint-initdb.d
#    healthcheck:
#      test:
#        [
#          "CMD",
#          "mysqladmin",
#          "ping",
#          "-uuser",
#          "-ppwd",
#          "-h",
#          "localhost",
#        ]
#      interval: 10s
#      timeout: 5s
#      retries: 10

  artist_mysql:
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=artist
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./data/mysql-artist:/var/lib/artist_mysql
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-ppwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10


  mongodb_podcast:
    image: mongo:8.0
    container_name: mongodb_podcast
    #    hostname: mongodb_podcast
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
#      - ./podcast-service/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro

    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pwd
      - MONGO_INITDB_DATABASE=podcast
    #      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
    #      - ME_CONFIG_MONGODB_ADMINPASSWORD=pwd
    #      - ME_CONFIG_MONGODB_SERVER=mongodb_podcast
    #      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    #      - ME_CONFIG_MONGODB_DATABASE=podcast
    #      - ME_CONFIG_MONGODB_USER=user
    #      - ME_CONFIG_MONGODB_PASSWORD=pwd
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
#  podcast_mysql:
#    image: mysql:8
#    ports:
#      - "3309:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=rootpass
#      - MYSQL_DATABASE=podcast
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=pwd
#    volumes:
#      - ./data/mysql-podcast:/var/lib/podcast_mysql
#      - ./data/init.d:/docker-entrypoint-initdb.d
#    healthcheck:
#      test:
#        [
#          "CMD",
#          "mysqladmin",
#          "ping",
#          "-uuser",
#          "-ppwd",
#          "-h",
#          "localhost",
#        ]
#      interval: 10s
#      timeout: 5s
#      retries: 10

  catalog_mysql:
    image: mysql:8
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=catalog
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./data/mysql-catalog:/var/lib/catalog_mysql
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-ppwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  ##############################################
################## phpmyadmin###################
#  phpmyadmin:
#    image: phpmyadmin:5.2.0
#    container_name: user_servicePHPMYADMIN
#    links:
#      - user_mysql
#    restart: always
#    ports:
#      - 5013:80
#    environment:
##      - PMA_ARBITRARY=1
#      - PMA_HOST=user_mysql
#
#    depends_on:
#      user_mysql:
#        condition: service_healthy
  pgadmin1:
    image: dpage/pgadmin4:latest # Or a specific version
    container_name: pgadmin1-user
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@konate.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - 9000:80
    depends_on:
      - user_postgres

  pgadmin2:
    image: dpage/pgadmin4:latest # Or a specific version
    container_name: pgadmin1-order
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@konate.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - 9001:80
    depends_on:
      - order_postgres

  phpmyadmin-artist:
    image: phpmyadmin:5.2.0
    container_name: artist_servicePHPMYADMIN
    links:
      - artist_mysql
    restart: always
    ports:
      - 5014:80
    environment:
      #      - PMA_ARBITRARY=1
      - PMA_HOST=artist_mysql

    depends_on:
      artist_mysql:
        condition: service_healthy


#  phpmyadmin-podcast:
#    image: phpmyadmin:5.2.0
#    container_name: podcast_servicePHPMYADMIN
#    links:
#      - podcast_mysql
#    restart: always
#    ports:
#      - 5015:80
#    environment:
#      #      - PMA_ARBITRARY=1
#      - PMA_HOST=podcast_mysql
#
#    depends_on:
#      podcast_mysql:
#        condition: service_healthy

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    #    hostname: mongo_express
    restart: always

    ports:
      - "8088:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pwd
      - ME_CONFIG_MONGODB_SERVER=mongodb_podcast
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    depends_on:
      mongodb_podcast:
        condition: service_healthy


  phpmyadmin-catalog:
    image: phpmyadmin:5.2.0
    container_name: catalog_servicePHPMYADMIN
    links:
      - catalog_mysql
    restart: always
    ports:
      - 5016:80
    environment:
      #      - PMA_ARBITRARY=1
      - PMA_HOST=catalog_mysql

    depends_on:
      catalog_mysql:
        condition: service_healthy




######## API GATEWAY ########
############################


  api-gateway:
    #    image: api-gateway:latest
    hostname: api-gateway
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - API_GATEWAY_USER_HOST=user
      - API_GATEWAY_ARTIST_HOST=artist
      - API_GATEWAY_PODCAST_HOST=podcast
      - API_GATEWAY_CATALOG_HOST=catalog
      - API_GATEWAY_USER_PORT=8080
      - API_GATEWAY_ARTIST_PORT=8080
      - API_GATEWAY_PODCAST_PORT=8080
      - API_GATEWAY_CATALOG_PORT=8080
      -
    depends_on:
      - user
      - artist
      - podcast
      - catalog
volumes:
  mongodb_data: { }
