# Default Configuration (No indentation for root keys)
app:
  artist:
    host: localhost
    port: 7001
  user:
    host: localhost
    port: 7002
  podcast:
    host: localhost
    port: 7003
  catalog:
    host: localhost
    port: 7004
  order:
    host: localhost
    port: 7005
  ad:
    host: localhost
    port: 7006

server:
  port: 8080
  error:
    include-message: always

---
# Docker Profile Configuration
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    hikari:
      initializationFailTimeout: 60000

app:
  artist:
    host: artist
    port: 8080
  user:
    host: user
    port: 8080
  podcast:
    host: podcast
    port: 8080
  catalog:
    host: catalog
    port: 8080
  order:
    host: order
    port: 8080
  ad:
    host: ad
    port: 8080