services:
  podcast:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: podcast
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://podcast_mysql/podcast
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pwd
    depends_on:
      podcast_mysql:
        condition: service_healthy

  podcast_mysql:
    image: mysql:8
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=podcast
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./data/mysql1:/var/lib/podcast_mysql
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-ppwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: podcast_servicePHPMYADMIN
    links:
      - podcast_mysql
    restart: always
    ports:
      - 5015:80
    environment:
#      - PMA_ARBITRARY=1
      - PMA_HOST=podcast_mysql

    depends_on:
      podcast_mysql:
        condition: service_healthy