services:
  artist:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: artist
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://artist_mysql/artist
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pwd
    depends_on:
      artist_mysql:
        condition: service_healthy

  artist_mysql:
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=artist
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./data/mysql1:/var/lib/artist_mysql
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-ppwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: artist_servicePHPMYADMIN
    links:
      - artist_mysql
    restart: always
    ports:
      - 5014:80
    environment:
#      - PMA_ARBITRARY=1
      - PMA_HOST=artist_mysql

    depends_on:
      artist_mysql:
        condition: service_healthy