# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.konate: DEBUG
    org.springframework.boot.test: DEBUG
    de.flapdoodle.embed.mongo: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


---


# for docker

spring:
    config:
      activate:
        on-profile: docker
    data:
      mongodb:
#        uri: mongodb_podcast://user:pwd@mongodb:27017/podcast
        host: mongodb_podcast
        port: 27017
        username: user
        password: pwd
        authentication-database: admin
        database: podcast
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver: DEBUG


#    datasource:
#      url: jdbc:mysql://podcast_mysql/podcast
#      username: user
#      password: pwd
#
#    jpa:
#      show-sql: true
#      hibernate:
#        ddl-auto: none   #use create to allow jpa to auto-generate from Entity classes; use none to use schema-h2.sql
#
#      defer-datasource-initialization: true
#
#    sql:
#      init:
#        platform: mysql
#        mode: always
#        schema-locations: classpath:schema.sql
#        data-locations: classpath:data.sql

server.port: 8080

spring.datasource.hikari.initializationFailTimeout: 60000



---
spring:
  config:
    activate:
      on-profile: test

  data:
    mongodb:
      host: localhost
      port: 0 # random port for embedded MongoDB
      database: podcastTestDb
      username: user
      password: pwd
      authentication-database: admin

      auto-index-creation: true
logging:
  level:
    root: INFO # or DEBUG if needed
    com.konate: DEBUG # Set to DEBUG or TRACE

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5
